import type { Song, CoverGrowthSong } from "@/types/domain"

export const mockSongs: Song[] = [
  {
    id: "song-1",
    title: "좋은 날",
    artist: "IU",
    genre: "발라드",
    difficulty: "hard",
    language: "ko",
    peakNote: "E5",
    rouletteTags: ["superHigh"],
    category: "ballad",
    bpm: 132,
    duration: "4:15",
    youtubeUrl: "jeqdYyvnTYg",
    releaseYear: 2010,
    lyrics: "어떤 말로 널 설명할 수 있을까\n아무 말도 필요없게 넌 예쁘다\n눈이 부셔 햇살보다 더 눈이 부셔",
  },
  {
    id: "song-2",
    title: "Love Dive",
    artist: "IVE",
    genre: "댄스",
    difficulty: "medium",
    language: "ko",
    peakNote: "A4",
    rouletteTags: ["superCute"],
    category: "kpop_idol",
    bpm: 125,
    duration: "2:58",
    youtubeUrl: "Y8JFxS1HlDo",
    releaseYear: 2022,
  },
  {
    id: "song-3",
    title: "밤하늘의 별을",
    artist: "경서",
    genre: "발라드",
    difficulty: "medium",
    language: "ko",
    peakNote: "D5",
    rouletteTags: ["emotionalBallad"],
    category: "ballad",
    bpm: 72,
    duration: "4:28",
    youtubeUrl: "HHKJv6k9bJc",
    releaseYear: 2022,
  },
  {
    id: "song-4",
    title: "새삥",
    artist: "지코",
    genre: "힙합",
    difficulty: "easy",
    language: "ko",
    peakNote: "G4",
    rouletteTags: ["meme"],
    category: "hiphop",
    bpm: 120,
    duration: "3:12",
    youtubeUrl: "ZlwB4_o8rP0",
    releaseYear: 2018,
  },
  {
    id: "song-5",
    title: "Ditto",
    artist: "NewJeans",
    genre: "팝",
    difficulty: "easy",
    language: "ko",
    peakNote: "F4",
    rouletteTags: [],
    category: "kpop_idol",
    bpm: 110,
    duration: "3:05",
    youtubeUrl: "Km71Rr9K-Bw",
    releaseYear: 2022,
  },
  {
    id: "song-6",
    title: "취중고백",
    artist: "김동률",
    genre: "발라드",
    difficulty: "medium",
    language: "ko",
    peakNote: "C5",
    rouletteTags: ["emotionalBallad"],
    category: "ballad",
    bpm: 90,
    duration: "4:20",
    youtubeUrl: "7wA2m_tJk1M",
    releaseYear: 2003,
  },
  {
    id: "song-7",
    title: "파이팅 해야지",
    artist: "부석순",
    genre: "댄스",
    difficulty: "easy",
    language: "ko",
    peakNote: "B4",
    rouletteTags: [],
    category: "kpop_idol",
    bpm: 128,
    duration: "3:18",
    youtubeUrl: "mBXBOLG06Wc",
    releaseYear: 2023,
  },
  {
    id: "song-8",
    title: "Dynamite",
    artist: "BTS",
    genre: "팝",
    difficulty: "medium",
    language: "en",
    peakNote: "C5",
    rouletteTags: [],
    category: "kpop_idol",
    bpm: 114,
    duration: "3:19",
    youtubeUrl: "gdZLi9oWNZg",
    releaseYear: 2020,
  },
  {
    id: "song-9",
    title: "첫눈",
    artist: "EXO",
    genre: "발라드",
    difficulty: "medium",
    language: "ko",
    peakNote: "D5",
    rouletteTags: [],
    category: "ballad",
    bpm: 76,
    duration: "3:47",
    youtubeUrl: "OpT_Zf5t7K8",
    releaseYear: 2013,
  },
  {
    id: "song-10",
    title: "사랑은 늘 도망가",
    artist: "이무진",
    genre: "발라드",
    difficulty: "hard",
    language: "ko",
    peakNote: "E5",
    rouletteTags: [],
    category: "ballad",
    bpm: 88,
    duration: "4:02",
    youtubeUrl: "Jj7pDNDuoJ0",
    releaseYear: 2021,
  },
  {
    id: "song-11",
    title: "Butter",
    artist: "BTS",
    genre: "댄스",
    difficulty: "medium",
    language: "en",
    peakNote: "B4",
    rouletteTags: [],
    category: "dance_pop",
    bpm: 110,
    duration: "2:44",
    youtubeUrl: "WMweEpGlu_U",
    releaseYear: 2021,
  },
  {
    id: "song-12",
    title: "Cry For Me",
    artist: "TWICE",
    genre: "댄스",
    difficulty: "medium",
    language: "ko",
    peakNote: "C5",
    rouletteTags: [],
    category: "kpop_idol",
    bpm: 120,
    duration: "3:26",
    youtubeUrl: "FF50-LY2Kro",
    releaseYear: 2020,
  },
]

export const mockCoverGrowthSongs: CoverGrowthSong[] = [
  {
    ...mockSongs[0],
    id: "cover-1",
    coverArtist: "SongBird",
    vocalStyle: ["청아한", "섬세한 감성"],
    growthPoint: "감정 표현력이 돋보이는 커버입니다",
    youtubeUrl: "https://youtube.com",
    coverThumbnailUrl: "https://images.unsplash.com/photo-1516280440614-6697288d5d38?w=800&q=80",
    views: "15.2만",
    likes: "3.5천",
    comments: "420",
  },
  {
    ...mockSongs[7],
    id: "cover-2",
    coverArtist: "RockStar_K",
    vocalStyle: ["파워풀", "시원한 고음"],
    growthPoint: "다이내믹한 리듬감이 특징입니다",
    youtubeUrl: "https://youtube.com",
    coverThumbnailUrl: "https://images.unsplash.com/photo-1493225255756-d9584f8606e9?w=800&q=80",
    views: "8.4만",
    likes: "1.2천",
    comments: "156",
  },
  {
    ...mockSongs[2],
    id: "cover-3",
    coverArtist: "JazzyMoon",
    vocalStyle: ["허스키", "R&B 소울"],
    growthPoint: "독특한 음색으로 재해석했습니다",
    youtubeUrl: "https://youtube.com",
    coverThumbnailUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&q=80",
    views: "23만",
    likes: "8.1천",
    comments: "952",
  },
  {
    ...mockSongs[4],
    id: "cover-4",
    coverArtist: "DailyOat",
    vocalStyle: ["담백한", "편안한"],
    growthPoint: "안정적인 호흡이 인상적입니다",
    youtubeUrl: "https://youtube.com",
    coverThumbnailUrl: "https://images.unsplash.com/photo-1485579149621-3123dd979885?w=800&q=80",
    views: "5.7만",
    likes: "980",
    comments: "84",
  },
  {
    ...mockSongs[5],
    id: "cover-5",
    coverArtist: "HighNoteMaster",
    vocalStyle: ["교과서 정석", "깔끔한"],
    growthPoint: "정확한 음정과 박자를 배울 수 있습니다",
    youtubeUrl: "https://youtube.com",
    coverThumbnailUrl: "https://images.unsplash.com/photo-1520697843387-9b2f654b9d03?w=800&q=80",
    views: "45만",
    likes: "1.5만",
    comments: "2.1천",
  },
]
